// 批量把 project/backpack 新键翻译写入所有语言文件
const fs = require("fs");
const path = require("path");

const dir = "D:/DEV/bbs_clean/src/client/resources/assets/bbs/assets/strings";

const T = {
  ar_ar: {
    "bbs.ui.project.title": "المشاريع",
    "bbs.ui.project.create": "إنشاء مشروع",
    "bbs.ui.project.delete": "حذف",
    "bbs.ui.project.open": "فتح",
    "bbs.ui.project.name": "اسم المشروع",
    "bbs.ui.project.empty": "لا توجد مشاريع بعد. أنشئ واحداً للبدء!",
    "bbs.ui.project.current": "المشروع الحالي: %s",
    "bbs.ui.project.confirm_delete": "حذف المشروع \"%s\"? سيتم فقدان جميع بياناته!",
    "bbs.ui.main_menu.projects": "المشاريع",
    "bbs.ui.backpack.title": "حقيبة الظهر",
    "bbs.ui.backpack.export": "تصدير إلى الحقيبة",
    "bbs.ui.backpack.import": "استيراد",
    "bbs.ui.backpack.delete": "حذف",
    "bbs.ui.backpack.empty": "الحقيبة فارغة. صدّر شيئاً من مشروع!",
    "bbs.ui.backpack.exported": "تم تصدير جميع فئات الأشكال من المشروع الحالي إلى الحقيبة.",
    "bbs.ui.backpack.imported": "تم استيراد \"%s\" إلى المشروع الحالي."
  },
  de_de: {
    "bbs.ui.project.title": "Projekte",
    "bbs.ui.project.create": "Projekt erstellen",
    "bbs.ui.project.delete": "Löschen",
    "bbs.ui.project.open": "Öffnen",
    "bbs.ui.project.name": "Projektname",
    "bbs.ui.project.empty": "Noch keine Projekte. Erstelle eins, um zu starten!",
    "bbs.ui.project.current": "Aktuelles Projekt: %s",
    "bbs.ui.project.confirm_delete": "Projekt \"%s\" löschen? Alle Daten gehen verloren!",
    "bbs.ui.main_menu.projects": "Projekte",
    "bbs.ui.backpack.title": "Rucksack",
    "bbs.ui.backpack.export": "In den Rucksack exportieren",
    "bbs.ui.backpack.import": "Importieren",
    "bbs.ui.backpack.delete": "Löschen",
    "bbs.ui.backpack.empty": "Der Rucksack ist leer. Exportiere etwas aus einem Projekt!",
    "bbs.ui.backpack.exported": "Alle Formular-Kategorien des aktuellen Projekts wurden in den Rucksack exportiert.",
    "bbs.ui.backpack.imported": "\"%s\" wurde in das aktuelle Projekt importiert."
  },
  es_es: {
    "bbs.ui.project.title": "Proyectos",
    "bbs.ui.project.create": "Crear proyecto",
    "bbs.ui.project.delete": "Eliminar",
    "bbs.ui.project.open": "Abrir",
    "bbs.ui.project.name": "Nombre del proyecto",
    "bbs.ui.project.empty": "Aún no hay proyectos. ¡Crea uno para empezar!",
    "bbs.ui.project.current": "Proyecto actual: %s",
    "bbs.ui.project.confirm_delete": "¿Eliminar el proyecto \"%s\"? ¡Todos sus datos se perderán!",
    "bbs.ui.main_menu.projects": "Proyectos",
    "bbs.ui.backpack.title": "Mochila",
    "bbs.ui.backpack.export": "Exportar a la mochila",
    "bbs.ui.backpack.import": "Importar",
    "bbs.ui.backpack.delete": "Eliminar",
    "bbs.ui.backpack.empty": "La mochila está vacía. ¡Exporta algo de un proyecto!",
    "bbs.ui.backpack.exported": "Todas las categorías de formas del proyecto actual se exportaron a la mochila.",
    "bbs.ui.backpack.imported": "Se importó \"%s\" al proyecto actual."
  },
  fr_fr: {
    "bbs.ui.project.title": "Projets",
    "bbs.ui.project.create": "Créer un projet",
    "bbs.ui.project.delete": "Supprimer",
    "bbs.ui.project.open": "Ouvrir",
    "bbs.ui.project.name": "Nom du projet",
    "bbs.ui.project.empty": "Aucun projet pour l'instant. Créez-en un pour commencer !",
    "bbs.ui.project.current": "Projet actuel : %s",
    "bbs.ui.project.confirm_delete": "Supprimer le projet « %s » ? Toutes ses données seront perdues !",
    "bbs.ui.main_menu.projects": "Projets",
    "bbs.ui.backpack.title": "Sac à dos",
    "bbs.ui.backpack.export": "Exporter vers le sac à dos",
    "bbs.ui.backpack.import": "Importer",
    "bbs.ui.backpack.delete": "Supprimer",
    "bbs.ui.backpack.empty": "Le sac à dos est vide. Exportez quelque chose d'un projet !",
    "bbs.ui.backpack.exported": "Toutes les catégories de formes du projet actuel ont été exportées vers le sac à dos.",
    "bbs.ui.backpack.imported": "« %s » a été importé dans le projet actuel."
  },
  hu_hu: {
    "bbs.ui.project.title": "Projektek",
    "bbs.ui.project.create": "Projekt létrehozása",
    "bbs.ui.project.delete": "Törlés",
    "bbs.ui.project.open": "Megnyitás",
    "bbs.ui.project.name": "Projekt neve",
    "bbs.ui.project.empty": "Még nincsenek projektek. Hozz létre egyet a kezdéshez!",
    "bbs.ui.project.current": "Jelenlegi projekt: %s",
    "bbs.ui.project.confirm_delete": "Törlöd a \"%s\" projektet? Minden adata elveszik!",
    "bbs.ui.main_menu.projects": "Projektek",
    "bbs.ui.backpack.title": "Hátizsák",
    "bbs.ui.backpack.export": "Exportálás a hátizsákba",
    "bbs.ui.backpack.import": "Importálás",
    "bbs.ui.backpack.delete": "Törlés",
    "bbs.ui.backpack.empty": "A hátizsák üres. Exportálj valamit egy projektből!",
    "bbs.ui.backpack.exported": "Az aktuális projekt összes formakategóriája exportálva a hátizsákba.",
    "bbs.ui.backpack.imported": "\"%s\" importálva az aktuális projektbe."
  },
  id_id: {
    "bbs.ui.project.title": "Proyek",
    "bbs.ui.project.create": "Buat proyek",
    "bbs.ui.project.delete": "Hapus",
    "bbs.ui.project.open": "Buka",
    "bbs.ui.project.name": "Nama proyek",
    "bbs.ui.project.empty": "Belum ada proyek. Buat satu untuk memulai!",
    "bbs.ui.project.current": "Proyek saat ini: %s",
    "bbs.ui.project.confirm_delete": "Hapus proyek \"%s\"? Semua datanya akan hilang!",
    "bbs.ui.main_menu.projects": "Proyek",
    "bbs.ui.backpack.title": "Ransel",
    "bbs.ui.backpack.export": "Ekspor ke ransel",
    "bbs.ui.backpack.import": "Impor",
    "bbs.ui.backpack.delete": "Hapus",
    "bbs.ui.backpack.empty": "Ransel kosong. Ekspor sesuatu dari proyek!",
    "bbs.ui.backpack.exported": "Semua kategori bentuk dari proyek saat ini diekspor ke ransel.",
    "bbs.ui.backpack.imported": "\"%s\" diimpor ke proyek saat ini."
  },
  ko_kr: {
    "bbs.ui.project.title": "프로젝트",
    "bbs.ui.project.create": "프로젝트 만들기",
    "bbs.ui.project.delete": "삭제",
    "bbs.ui.project.open": "열기",
    "bbs.ui.project.name": "프로젝트 이름",
    "bbs.ui.project.empty": "아직 프로젝트가 없습니다. 시작하려면 하나 만드세요!",
    "bbs.ui.project.current": "현재 프로젝트: %s",
    "bbs.ui.project.confirm_delete": "\"%s\" 프로젝트를 삭제하시겠습니까? 모든 데이터가 손실됩니다!",
    "bbs.ui.main_menu.projects": "프로젝트",
    "bbs.ui.backpack.title": "배낭",
    "bbs.ui.backpack.export": "배낭으로 내보내기",
    "bbs.ui.backpack.import": "가져오기",
    "bbs.ui.backpack.delete": "삭제",
    "bbs.ui.backpack.empty": "배낭이 비어 있습니다. 프로젝트에서 무언가를 내보내세요!",
    "bbs.ui.backpack.exported": "현재 프로젝트의 모든 형태 범주를 배낭으로 내보냈습니다.",
    "bbs.ui.backpack.imported": "\"%s\"을(를) 현재 프로젝트로 가져왔습니다."
  },
  pl_pl: {
    "bbs.ui.project.title": "Projekty",
    "bbs.ui.project.create": "Utwórz projekt",
    "bbs.ui.project.delete": "Usuń",
    "bbs.ui.project.open": "Otwórz",
    "bbs.ui.project.name": "Nazwa projektu",
    "bbs.ui.project.empty": "Brak projektów. Utwórz jeden, aby zacząć!",
    "bbs.ui.project.current": "Bieżący projekt: %s",
    "bbs.ui.project.confirm_delete": "Usunąć projekt \"%s\"? Wszystkie dane zostaną utracone!",
    "bbs.ui.main_menu.projects": "Projekty",
    "bbs.ui.backpack.title": "Plecak",
    "bbs.ui.backpack.export": "Eksportuj do plecaka",
    "bbs.ui.backpack.import": "Importuj",
    "bbs.ui.backpack.delete": "Usuń",
    "bbs.ui.backpack.empty": "Plecak jest pusty. Wyeksportuj coś z projektu!",
    "bbs.ui.backpack.exported": "Wszystkie kategorie form bieżącego projektu wyeksportowano do plecaka.",
    "bbs.ui.backpack.imported": "Zaimportowano \"%s\" do bieżącego projektu."
  },
  pt_br: {
    "bbs.ui.project.title": "Projetos",
    "bbs.ui.project.create": "Criar projeto",
    "bbs.ui.project.delete": "Excluir",
    "bbs.ui.project.open": "Abrir",
    "bbs.ui.project.name": "Nome do projeto",
    "bbs.ui.project.empty": "Ainda não há projetos. Crie um para começar!",
    "bbs.ui.project.current": "Projeto atual: %s",
    "bbs.ui.project.confirm_delete": "Excluir o projeto \"%s\"? Todos os dados serão perdidos!",
    "bbs.ui.main_menu.projects": "Projetos",
    "bbs.ui.backpack.title": "Mochila",
    "bbs.ui.backpack.export": "Exportar para a mochila",
    "bbs.ui.backpack.import": "Importar",
    "bbs.ui.backpack.delete": "Excluir",
    "bbs.ui.backpack.empty": "A mochila está vazia. Exporte algo de um projeto!",
    "bbs.ui.backpack.exported": "Todas as categorias de formas do projeto atual foram exportadas para a mochila.",
    "bbs.ui.backpack.imported": "\"%s\" foi importado para o projeto atual."
  },
  pt_pt: {
    "bbs.ui.project.title": "Projetos",
    "bbs.ui.project.create": "Criar projeto",
    "bbs.ui.project.delete": "Eliminar",
    "bbs.ui.project.open": "Abrir",
    "bbs.ui.project.name": "Nome do projeto",
    "bbs.ui.project.empty": "Ainda não há projetos. Crie um para começar!",
    "bbs.ui.project.current": "Projeto atual: %s",
    "bbs.ui.project.confirm_delete": "Eliminar o projeto \"%s\"? Todos os dados serão perdidos!",
    "bbs.ui.main_menu.projects": "Projetos",
    "bbs.ui.backpack.title": "Mochila",
    "bbs.ui.backpack.export": "Exportar para a mochila",
    "bbs.ui.backpack.import": "Importar",
    "bbs.ui.backpack.delete": "Eliminar",
    "bbs.ui.backpack.empty": "A mochila está vazia. Exporte algo de um projeto!",
    "bbs.ui.backpack.exported": "Todas as categorias de formas do projeto atual foram exportadas para a mochila.",
    "bbs.ui.backpack.imported": "\"%s\" foi importado para o projeto atual."
  },
  ru_ru: {
    "bbs.ui.project.title": "Проекты",
    "bbs.ui.project.create": "Создать проект",
    "bbs.ui.project.delete": "Удалить",
    "bbs.ui.project.open": "Открыть",
    "bbs.ui.project.name": "Название проекта",
    "bbs.ui.project.empty": "Пока нет проектов. Создайте один, чтобы начать!",
    "bbs.ui.project.current": "Текущий проект: %s",
    "bbs.ui.project.confirm_delete": "Удалить проект \"%s\"? Все данные будут потеряны!",
    "bbs.ui.main_menu.projects": "Проекты",
    "bbs.ui.backpack.title": "Рюкзак",
    "bbs.ui.backpack.export": "Экспортировать в рюкзак",
    "bbs.ui.backpack.import": "Импортировать",
    "bbs.ui.backpack.delete": "Удалить",
    "bbs.ui.backpack.empty": "Рюкзак пуст. Экспортируйте что-нибудь из проекта!",
    "bbs.ui.backpack.exported": "Все категории форм текущего проекта экспортированы в рюкзак.",
    "bbs.ui.backpack.imported": "\"%s\" импортирован в текущий проект."
  },
  th_th: {
    "bbs.ui.project.title": "โปรเจกต์",
    "bbs.ui.project.create": "สร้างโปรเจกต์",
    "bbs.ui.project.delete": "ลบ",
    "bbs.ui.project.open": "เปิด",
    "bbs.ui.project.name": "ชื่อโปรเจกต์",
    "bbs.ui.project.empty": "ยังไม่มีโปรเจกต์ สร้างหนึ่งรายการเพื่อเริ่ม!",
    "bbs.ui.project.current": "โปรเจกต์ปัจจุบัน: %s",
    "bbs.ui.project.confirm_delete": "ลบโปรเจกต์ \"%s\"? ข้อมูลทั้งหมดจะสูญหาย!",
    "bbs.ui.main_menu.projects": "โปรเจกต์",
    "bbs.ui.backpack.title": "กระเป๋าเป้",
    "bbs.ui.backpack.export": "ส่งออกไปยังกระเป๋าเป้",
    "bbs.ui.backpack.import": "นำเข้า",
    "bbs.ui.backpack.delete": "ลบ",
    "bbs.ui.backpack.empty": "กระเป๋าเป้ว่างเปล่า ส่งออกบางอย่างจากโปรเจกต์!",
    "bbs.ui.backpack.exported": "ส่งออกหมวดหมู่ฟอร์มทั้งหมดของโปรเจกต์ปัจจุบันไปยังกระเป๋าเป้แล้ว",
    "bbs.ui.backpack.imported": "นำเข้า \"%s\" ไปยังโปรเจกต์ปัจจุบันแล้ว"
  },
  tr_tr: {
    "bbs.ui.project.title": "Projeler",
    "bbs.ui.project.create": "Proje oluştur",
    "bbs.ui.project.delete": "Sil",
    "bbs.ui.project.open": "Aç",
    "bbs.ui.project.name": "Proje adı",
    "bbs.ui.project.empty": "Henüz proje yok. Başlamak için bir tane oluşturun!",
    "bbs.ui.project.current": "Geçerli proje: %s",
    "bbs.ui.project.confirm_delete": "\"%s\" projesi silinsin mi? Tüm verileri kaybolacak!",
    "bbs.ui.main_menu.projects": "Projeler",
    "bbs.ui.backpack.title": "Sırt çantası",
    "bbs.ui.backpack.export": "Sırt çantasına dışa aktar",
    "bbs.ui.backpack.import": "İçe aktar",
    "bbs.ui.backpack.delete": "Sil",
    "bbs.ui.backpack.empty": "Sırt çantası boş. Bir projeden bir şey dışa aktarın!",
    "bbs.ui.backpack.exported": "Geçerli projenin tüm form kategorileri sırt çantasına dışa aktarıldı.",
    "bbs.ui.backpack.imported": "\"%s\" geçerli projeye içe aktarıldı."
  },
  uk_ua: {
    "bbs.ui.project.title": "Проєкти",
    "bbs.ui.project.create": "Створити проєкт",
    "bbs.ui.project.delete": "Видалити",
    "bbs.ui.project.open": "Відкрити",
    "bbs.ui.project.name": "Назва проєкту",
    "bbs.ui.project.empty": "Поки немає проєктів. Створіть один, щоб почати!",
    "bbs.ui.project.current": "Поточний проєкт: %s",
    "bbs.ui.project.confirm_delete": "Видалити проєкт \"%s\"? Усі дані буде втрачено!",
    "bbs.ui.main_menu.projects": "Проєкти",
    "bbs.ui.backpack.title": "Рюкзак",
    "bbs.ui.backpack.export": "Експортувати в рюкзак",
    "bbs.ui.backpack.import": "Імпортувати",
    "bbs.ui.backpack.delete": "Видалити",
    "bbs.ui.backpack.empty": "Рюкзак порожній. Експортуйте щось із проєкту!",
    "bbs.ui.backpack.exported": "Усі категорії форм поточного проєкту експортовано в рюкзак.",
    "bbs.ui.backpack.imported": "\"%s\" імпортовано в поточний проєкт."
  },
  ur_pk: {
    "bbs.ui.project.title": "منصوبے",
    "bbs.ui.project.create": "منصوبہ بنائیں",
    "bbs.ui.project.delete": "حذف کریں",
    "bbs.ui.project.open": "کھولیں",
    "bbs.ui.project.name": "منصوبے کا نام",
    "bbs.ui.project.empty": "ابھی کوئی منصوبہ نہیں۔ شروع کرنے کے لیے ایک بنائیں!",
    "bbs.ui.project.current": "موجودہ منصوبہ: %s",
    "bbs.ui.project.confirm_delete": "منصوبہ \"%s\" حذف کریں؟ اس کا تمام ڈیٹا ضائع ہو جائے گا!",
    "bbs.ui.main_menu.projects": "منصوبے",
    "bbs.ui.backpack.title": "بیگ",
    "bbs.ui.backpack.export": "بیگ میں برآمد کریں",
    "bbs.ui.backpack.import": "درآمد کریں",
    "bbs.ui.backpack.delete": "حذف کریں",
    "bbs.ui.backpack.empty": "بیگ خالی ہے۔ کسی منصوبے سے کچھ برآمد کریں!",
    "bbs.ui.backpack.exported": "موجودہ منصوبے کے تمام فارم زمرے بیگ میں برآمد کر دیے گئے۔",
    "bbs.ui.backpack.imported": "\"%s\" موجودہ منصوبے میں درآمد کر دیا گیا۔"
  },
  vi_vn: {
    "bbs.ui.project.title": "Dự án",
    "bbs.ui.project.create": "Tạo dự án",
    "bbs.ui.project.delete": "Xóa",
    "bbs.ui.project.open": "Mở",
    "bbs.ui.project.name": "Tên dự án",
    "bbs.ui.project.empty": "Chưa có dự án nào. Tạo một dự án để bắt đầu!",
    "bbs.ui.project.current": "Dự án hiện tại: %s",
    "bbs.ui.project.confirm_delete": "Xóa dự án \"%s\"? Toàn bộ dữ liệu sẽ bị mất!",
    "bbs.ui.main_menu.projects": "Dự án",
    "bbs.ui.backpack.title": "Ba lô",
    "bbs.ui.backpack.export": "Xuất vào ba lô",
    "bbs.ui.backpack.import": "Nhập",
    "bbs.ui.backpack.delete": "Xóa",
    "bbs.ui.backpack.empty": "Ba lô trống. Xuất thứ gì đó từ một dự án!",
    "bbs.ui.backpack.exported": "Tất cả danh mục biểu mẫu của dự án hiện tại đã được xuất vào ba lô.",
    "bbs.ui.backpack.imported": "Đã nhập \"%s\" vào dự án hiện tại."
  },
  zh_tw: {
    "bbs.ui.project.title": "專案",
    "bbs.ui.project.create": "建立專案",
    "bbs.ui.project.delete": "刪除",
    "bbs.ui.project.open": "開啟",
    "bbs.ui.project.name": "專案名稱",
    "bbs.ui.project.empty": "還沒有專案，建立一個開始吧！",
    "bbs.ui.project.current": "目前專案: %s",
    "bbs.ui.project.confirm_delete": "刪除專案 \"%s\"? 其所有資料都將遺失！",
    "bbs.ui.main_menu.projects": "專案",
    "bbs.ui.backpack.title": "背包",
    "bbs.ui.backpack.export": "匯出到背包",
    "bbs.ui.backpack.import": "匯入",
    "bbs.ui.backpack.delete": "刪除",
    "bbs.ui.backpack.empty": "背包是空的，先從專案匯出一些東西吧！",
    "bbs.ui.backpack.exported": "已把目前專案的所有形態分類匯出到背包。",
    "bbs.ui.backpack.imported": "已將 \"%s\" 匯入到目前專案。"
  }
};

const KEYS = [
  "bbs.ui.project.title", "bbs.ui.project.create", "bbs.ui.project.delete",
  "bbs.ui.project.open", "bbs.ui.project.name", "bbs.ui.project.empty",
  "bbs.ui.project.current", "bbs.ui.project.confirm_delete",
  "bbs.ui.main_menu.projects", "bbs.ui.backpack.title", "bbs.ui.backpack.export",
  "bbs.ui.backpack.import", "bbs.ui.backpack.delete", "bbs.ui.backpack.empty",
  "bbs.ui.backpack.exported", "bbs.ui.backpack.imported"
];

for (const [lang, dict] of Object.entries(T)) {
  const file = path.join(dir, lang + ".json");
  if (!fs.existsSync(file)) { console.log("SKIP", lang); continue; }
  let content = fs.readFileSync(file, "utf-8");
  const lines = KEYS.map(k => `    "${k}": "${dict[k]}"`);
  const idx = content.trimEnd().lastIndexOf("}");
  content = content.slice(0, idx) + lines.join(",\n") + "\n" + content.slice(idx);
  fs.writeFileSync(file, content, "utf-8");
  console.log("OK", lang);
}
